name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check go environment
      run: go env
    - name: Install packr dependency
      run: |
        go get -u github.com/gobuffalo/packr/packr
        export PATH="/home/runner/go/bin:$PATH"
        which packr
    - name: Verify Modules
      run: |
        cd ./scoring_engine/app
        go mod verify
    - name: Build Scoring Engine
      run: |
        cd ./scoring_engine/app
        export PATH="/home/runner/go/bin:$PATH"
        npm install
        npm run build
        packr build -o scoring-engine -v .
