name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: "0 9 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Scoring Engine
      run: |
        cd ./scoring_engine/app
        go build -o scoring-engine -v .
        go mod verify
